#!/usr/bin/env bash

set -eux

RELEASE_PATH=$1
RELEASE_NAME=$2
PACKAGE_NAME=$3
FILE=$4
DESTINATION_PATH=$5

tar xf ${RELEASE_PATH}/${RELEASE_NAME}.tgz -C ${RELEASE_PATH}
mkdir -p ${RELEASE_PATH}
tar xf ${RELEASE_PATH}/packages/${PACKAGE_NAME}.tgz -C ${RELEASE_PATH}
cp ${RELEASE_PATH}/${PACKAGE_NAME}/${FILE} ${DESTINATION_PATH}
